name: chorus_app
description: For pentecostes church.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^0.3.7
  sqflite: ^1.3.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.4
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/

  fonts:
    - family: ABeeZee Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 300
    - family: Lobster Regular
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
